#%RAML 1.0
title: Banking Accounts Process API
version: v1.0
types: !include dataTypes.raml

/accounts/aggregate:
  displayName: aggregateAccounts
  get:
    description: Return aggregated Accounts by user SSN  
    queryParameters:
      ssn:
        type: SSN
        example: 123-45-6789
    responses:
      200:
        body:
          application/json:
            type: Account[]
            example: !include ./examples/get_accounts_aggregate_example.json
/transactions/aggregate:
  displayName: aggregateTransactions
  get:
    description: Return aggregated Transactions by user SSN  
    queryParameters:
      ssn:
        type: SSN
        example: 123-45-6789
    responses:
      200:
        body:
          application/json:
            type: Transaction[]
            example: !include ./examples/get_transactions_aggregate_example.json
