#%RAML 1.0
title: template-banking-pisp
version: v1
baseUri: localhost:8081/api/{version}/payment
protocols: HTTPS


/key:
  get:
    queryParameters:
      client_id: 
        required: true
        description: Client ID of the registered App.
      client_secret: 
        required: true
        description: Client ID of the registered App.
    responses: 
      200:
        body:
          application/json:
          

/initiate:
  description: |
    Initiates payment to payee from consumer. Before transfer of funds can be processed, customer authentication and consent must occur. A nonce will be used to prevent replay attacks and inadvertent duplicate transfers.
    
    The payee information is provided to the API as a JWT token with the set of payment claims. The JWT token (https://jwt.io/introduction/) is signed with the client secret of the registered app to ensure that it is not tampered with.
    
    This endpoint finally redirects to the redirect_url provided as part of the inputs. The redirect_url should match the one registered by the client. It will return transaction_id and status.
  get:
    queryParameters:
      client_id: 
        required: true
        description: Client ID of the registered App.
      redirect_uri:
        required: true
        description: Redirect URI defined with your registered App.
      paymentId:
        required: true
        description: ID generated in the first step to link payment Token to the one time password.
        
      scope:
        required: false
        description: |
          Scope of the Access Token requested. Space separated list of the following options: openid, accounts, payment.
        default: 'openid accounts payment'
        enum: ['openid accounts payment']
      locale:
        required: false
        description: Locale to be used during authorization process.
        enum: [en,es]
        default: en
      state:
        required: false
        description: unique ID to maintain state between asynchronous requests.
      request:
        required: true
        description: |
          The JWT token with all the relevant payment claims signed with the client secret of the app. 
          After decoding, the request should provide payment info and be similar to:
          
          {
           "iss": "https://demo-merchant.example.com", // issuer's
           "aud": "https://example-bank.cloudhub.io",  // recipient
           "client_id": "grOmvYA89jsdhkshdIYhGtpvztofAAjz", 
           "redirect_uri": "http://localhost/", 
           "scope": "openid accounts payment", //requested scopes
           "state": "af0ifjsldkj", //unique state to connect request and response
           "iat":  "1462517645809"  // issued at
           "claims": {
               "payment": {
                   "type": "sepa_credit_transfer", 
                   "to": {
                       "account_number": "31926819", //receiver account id
                       "bank_id": "gk.40.uk",
                       "bic": "NWBKGB2L", 
                       "IBAN": "GB29NWBK60161331926819", 
                       "name": "demo merchant online store" 
                   },
                   "value": {
                       "currency": "GBP", 
                       "amount": "200"
                   },
                   "additional": {
                       "subject": "Online Purchase",     //transfer description
                       "booking_code": "2SFBJ28553",     //transfer booking code
                       "booking_date": "1462517645809",  //transfer booking date
                       "value_date": "1462517645809"     //transfer value date
                   }              
                }
            }
          }
        
    responses:
      302:
        headers:
          Location:   
 
/consent:
  get:
    description: User is shown the list of his/her accounts and information about payment. User can confirm or deny the payment.
    queryParameters: 
      access_token:
        required: false
        description: Access token issued by Authorization Server  to make payment
      state: 
        required: false
        description: Contains the payment ID to retrieve payment token sent during initiation phase
    responses:
      200: 
        body: 
          text/html:
          
          
/processPayment:
  post:
    description: User is shown the list of his/her accounts and information about payment. User can confirm or deny the payment.
    body:
      application/x-www-form-urlencoded:
        properties:
          access_token:
            description: Access token that proves user identity.
          paymentId:
            description: Payment ID is used as a key for the payment information. This should be populated by the previous flows.
          account_id:
            description: Account ID which should be used for payment.
      
    responses:
      302: 
      
               